spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PRONTUARIO
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
